# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/reference/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/guides/orchestrate/jobs-steps/#jobs-overview & https://circleci.com/docs/reference/configuration-reference/#jobs
jobs:
  # renamed from 'build' to 'say-hello' to match the workflow below
  say-hello:
    docker:
      - image: cimg/openjdk:25.0.0
    steps:
      - checkout
      
      - run: 
          name: "Check Java Version"
          command: java --version
          
      - run:
          name: "Say hello"
          command: echo "Hello, World!"
          
      - run:
          name: "Ejecutar prueba"
          command: mvn test

workflows:
  say-hello-workflow:
    jobs:
      - say-hello


# Orchestrate jobs using workflows
# See: https://circleci.com/docs/guides/orchestrate/workflows/ & https://circleci.com/docs/reference/configuration-reference/#workflows
workflows:
  say-hello-workflow: # This is the name of the workflow, feel free to change it to better match your workflow.
    # Inside the workflow, you define the jobs you want to run.
    jobs:
      - say-hello
